apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  selector:
    app: orders-api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api-stable
spec:
  selector:
    app: orders-api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api-canary
spec:
  selector:
    app: orders-api
  ports:
    - name: http
      port: 8080
      targetPort: http
